"""V2 steps 3--6: harness synthesis and verification orchestrator.

Wires the scan pieces into one runnable flow, one candidate at a time:

    candidate (file, function, category, expression)
      -> synth.py       LLM writes a scalar ESBMC harness      (1 paid API call)
      -> compat.py       harness runs on ESBMC-Python?
      -> ESBMC           verify the harness at module level
      -> ablation.py     SUCCESSFUL? was an __ESBMC_assume masking the bug?
      -> classification

There is no repository scanning here: the candidate list is the input. Where the
candidates come from (manual review, an exploration agent) is deliberately
outside the measured method, the same way BugsInPy supplies the cases in V1.
"""

from __future__ import annotations

import json
import tempfile
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from ..models import Finding
from ..preprocess import preprocess_file
from ..verification.esbmc_runner import run_esbmc_direct, run_esbmc_on_function
from .ablation import FAILED, AblationReport, ablate
from .compat import (
    EXPECTED_PROPERTY_MARKER,
    OUTCOME_CATEGORIES,
    VERDICT_UNSUPPORTED,
    check_harness,
    check_outcome_grounding,
)
from .driver_check import VERDICT_UNSUPPORTED as DRIVER_VERDICT_UNSUPPORTED
from .driver_check import check_driver_harness
from .synth import STYLE_DRIVER, HarnessSynthesizer

# Scan-specific classifications. Distinct from the V1 constants in models.py
# because "confirmed" here means "on the synthesized abstraction", not "on the
# original file".
CONFIRMED_ON_ABSTRACTION = "confirmed_on_abstraction"
# ESBMC found a violation in an OUTCOME_CATEGORIES candidate (incorrect_result,
# assertion_violation). check_harness() already rejects the bare-boolean shape
# (compat.py's _unconstrained_outcome_reasons), but that check only catches the
# harness's SYNTAX, not whether the grounding is real -- an LLM can satisfy it
# with e.g. `assert x == True` and stay just as disconnected from the real bug
# (EXP-03, docs/v2/experiment_log.md, 2026-09-04). A confirmation in these two
# categories is trusted only when check_outcome_grounding() finds a
# buggy-vs-expected comparison; otherwise it is demoted to this report label.
# The pipeline still runs end to end with no human input, it just declines to
# count weak outcome assertions as strong automatic claims.
CONFIRMED_UNVERIFIED = "confirmed_unverified"
# ESBMC's own --function/--assign-param-nondet (Flow B, verification/esbmc_runner.py)
# verifies the REAL source function directly, symbolic parameters generated by
# ESBMC itself -- no LLM harness, no abstraction gap to argue about. Tried
# before synthesis (_try_native); only usable when the file already has
# enough type-hint coverage for ESBMC-Python to convert it (measured
# 2026-09-05: ~16% of dataset/v2_real_world/detection functions qualify).
CONFIRMED_NATIVE = "confirmed_native"
SAFE_NATIVE = "safe_native"
# Verbatim-driver method (_try_driver): the LLM keeps the real function body
# untouched and writes only the symbolic driver -- nondet inputs, __ESBMC_assume
# preconditions, a plain-assert postcondition, main() called at module level.
# ESBMC then executes the real arithmetic/control flow. This is the reference
# PoC pattern (github.com/lucasccordeiro/vllm, harness/); it removes the
# expression-reconstruction abstraction gap the scalar synth carries and does
# not use __ESBMC_cover, so the marker/cover interaction (EXP-01) does not
# arise. Tried after _try_native, before the scalar synth fallback. Needs the
# real function to convert under ESBMC-Python (same gate as _try_native).
CONFIRMED_DRIVER = "confirmed_driver"
SAFE_DRIVER = "safe_driver"
OVER_RESTRICTED = "over_restricted"
SAFE_ON_ABSTRACTION = "safe_on_abstraction"
INVALID_HARNESS = "invalid_harness"
UNSUPPORTED_HARNESS = "unsupported_harness"
NO_PROPERTY = "no_property"
ESBMC_INCONCLUSIVE = "esbmc_inconclusive"
ESBMC_UNAVAILABLE = "esbmc_unavailable"
CANDIDATE_NOT_FOUND = "candidate_not_found"
SYNTH_FAILED = "synth_failed"

# Stage labels used to explain why a correctly detected label did not become an
# end-to-end confirmation.  Keep these independent from ``classification``:
# the latter describes the final verdict, while this field describes where the
# pipeline stopped trusting the hypothesis.
FAILURE_GROUNDING = "grounding"
FAILURE_SYNTHESIS = "synthesis"
FAILURE_VERIFICATION = "verification"
FAILURE_UNATTRIBUTED = "unattributed"

# A conclusive verdict ends the retry loop; a recoverable one triggers another
# synthesis attempt (the LLM output varies run to run).
_CONCLUSIVE = frozenset(
    {
        CONFIRMED_ON_ABSTRACTION,
        CONFIRMED_UNVERIFIED,
        CONFIRMED_DRIVER,
        SAFE_DRIVER,
        OVER_RESTRICTED,
        SAFE_ON_ABSTRACTION,
    }
)
_RECOVERABLE = frozenset(
    {INVALID_HARNESS, UNSUPPORTED_HARNESS, NO_PROPERTY, ESBMC_INCONCLUSIVE, SYNTH_FAILED}
)


@dataclass
class ScanCandidate:
    """One function to investigate, supplied from outside the measured method."""

    file: str
    function: str
    category: str
    expression: str = ""
    note: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> ScanCandidate:
        need = [k for k in ("file", "function", "category") if not data.get(k)]
        if need:
            raise ValueError(f"candidate missing field(s): {', '.join(need)}")
        return cls(
            file=str(data["file"]),
            function=str(data["function"]),
            category=str(data["category"]),
            expression=str(data.get("expression", "")),
            note=str(data.get("note", "")),
        )


@dataclass
class ScanCaseResult:
    """Outcome for one candidate after the full synth -> ESBMC -> ablation flow."""

    candidate: ScanCandidate
    classification: str
    failure_stage: str = ""
    harness: str = ""
    harness_path: str = ""
    compat_verdict: str = ""
    compat_reasons: list[str] = field(default_factory=list)
    esbmc_status: str = ""
    esbmc_summary: str = ""
    masking_assumptions: list[str] = field(default_factory=list)
    ablation_per_assumption: dict[str, str] = field(default_factory=dict)
    synth_model: str = ""
    synth_total_tokens: int | None = None
    synth_seconds: float = 0.0
    esbmc_seconds: float = 0.0
    attempts: int = 1
    attempt_history: list[dict] = field(default_factory=list)
    seconds: float = 0.0
    error: str = ""
    # Why the verbatim-driver tier did or did not produce this result. One of:
    # "" (driver disabled), "conclusive", "unsupported: <reason>",
    # "invalid xN: <reason>", "inconclusive: <esbmc summary>", "vacuous: 0 VCCs",
    # "synth-failed: <exc>". Set even when the tier fell through to scalar synth,
    # so a run can be sliced by driver applicability without re-instrumenting.
    driver_note: str = ""

    def __post_init__(self) -> None:
        if not self.failure_stage:
            self.failure_stage = _failure_stage_for_classification(self.classification)

    @classmethod
    def from_dict(cls, data: dict) -> ScanCaseResult:
        return cls(
            candidate=ScanCandidate.from_dict(data["candidate"]),
            classification=str(data["classification"]),
            failure_stage=str(data.get("failure_stage", "")),
            harness=str(data.get("harness", "")),
            harness_path=str(data.get("harness_path", "")),
            compat_verdict=str(data.get("compat_verdict", "")),
            compat_reasons=list(data.get("compat_reasons", [])),
            esbmc_status=str(data.get("esbmc_status", "")),
            esbmc_summary=str(data.get("esbmc_summary", "")),
            masking_assumptions=list(data.get("masking_assumptions", [])),
            ablation_per_assumption=dict(data.get("ablation_per_assumption", {})),
            synth_model=str(data.get("synth_model", "")),
            synth_total_tokens=data.get("synth_total_tokens"),
            synth_seconds=float(data.get("synth_seconds", 0.0)),
            esbmc_seconds=float(data.get("esbmc_seconds", 0.0)),
            attempts=int(data.get("attempts", 1)),
            attempt_history=list(data.get("attempt_history", [])),
            seconds=float(data.get("seconds", 0.0)),
            error=str(data.get("error", "")),
            driver_note=str(data.get("driver_note", "")),
        )

    def to_dict(self) -> dict:
        return {
            "candidate": {
                "file": self.candidate.file,
                "function": self.candidate.function,
                "category": self.candidate.category,
                "expression": self.candidate.expression,
                "note": self.candidate.note,
            },
            "classification": self.classification,
            "failure_stage": self.failure_stage,
            "harness": self.harness,
            "harness_path": self.harness_path,
            "compat_verdict": self.compat_verdict,
            "compat_reasons": self.compat_reasons,
            "esbmc_status": self.esbmc_status,
            "esbmc_summary": self.esbmc_summary,
            "masking_assumptions": self.masking_assumptions,
            "ablation_per_assumption": self.ablation_per_assumption,
            "synth_model": self.synth_model,
            "synth_total_tokens": self.synth_total_tokens,
            "synth_seconds": round(self.synth_seconds, 3),
            "esbmc_seconds": round(self.esbmc_seconds, 3),
            "attempts": self.attempts,
            "attempt_history": self.attempt_history,
            "seconds": round(self.seconds, 2),
            "error": self.error,
            "driver_note": self.driver_note,
        }


def load_candidates(path: str | Path) -> list[ScanCandidate]:
    """Read the candidate list. Accepts a bare JSON list or {"candidates": [...]}."""
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    items = raw.get("candidates", raw) if isinstance(raw, dict) else raw
    if not isinstance(items, list):
        raise TypeError("candidate file must be a JSON list or {'candidates': [...]}")
    return [ScanCandidate.from_dict(item) for item in items]


def _failure_stage_for_classification(classification: str) -> str:
    """Map a final verdict to the pipeline stage that prevented confirmation.

    ``confirmed_unverified`` is a grounding failure: ESBMC found a violation,
    but the outcome assertion did not have an independently grounded oracle.
    Harness validation and missing properties are synthesis failures.  A safe,
    inconclusive, unavailable, or over-restricted result is a verification
    outcome, even when the root cause may be an overly restrictive harness.
    """
    if classification in {CONFIRMED_UNVERIFIED, CANDIDATE_NOT_FOUND}:
        return FAILURE_GROUNDING
    if classification in {
        INVALID_HARNESS,
        UNSUPPORTED_HARNESS,
        NO_PROPERTY,
        SYNTH_FAILED,
    }:
        return FAILURE_SYNTHESIS
    if classification in {
        SAFE_NATIVE,
        SAFE_DRIVER,
        SAFE_ON_ABSTRACTION,
        OVER_RESTRICTED,
        ESBMC_INCONCLUSIVE,
        ESBMC_UNAVAILABLE,
    }:
        return FAILURE_VERIFICATION
    return ""


def _find_unit(units: list, function_name: str):
    """Match by simple name, tolerating a dotted qualname like 'Class.method'."""
    if function_name.strip().lower().startswith("module-level"):
        return next((unit for unit in units if getattr(unit, "kind", "function") == "module"), None)
    want = function_name.split(".")[-1]
    for unit in units:
        if unit.name == want or unit.qualname == function_name:
            return unit
    return None


def run_pipeline_scan(
    candidates: list[ScanCandidate],
    *,
    synthesizer: HarnessSynthesizer,
    esbmc_command: list[str] | None = None,
    bound: int = 5,
    timeout_seconds: int = 30,
    output_dir: str | Path,
    use_compat: bool = True,
    use_guards: bool = True,
    use_ablation: bool = True,
    use_driver: bool = True,
    synth_retries: int = 1,
    completed_results: dict[int, ScanCaseResult] | None = None,
    on_result: Callable[[int, ScanCaseResult], None] | None = None,
) -> list[ScanCaseResult]:
    """Run the scan flow over every candidate and return one result each.

    The three layers are independently toggleable so the ablation study can run
    synth-only, then +compat, +guards, +ablation and compare. ``synth_retries``
    is the number of extra synthesis attempts allowed when an attempt ends in a
    recoverable failure (invalid harness, ESBMC error) rather than a verdict.
    """
    harness_dir = Path(output_dir) / "harnesses"
    harness_dir.mkdir(parents=True, exist_ok=True)

    results: list[ScanCaseResult] = []
    for index, candidate in enumerate(candidates):
        if completed_results and index in completed_results:
            result = completed_results[index]
            print(f"[{index + 1}/{len(candidates)}] Retomada: {candidate.function} já concluído; pulando.")
        else:
            result = _run_one(
                candidate,
                index=index,
                synthesizer=synthesizer,
                esbmc_command=esbmc_command,
                bound=bound,
                timeout_seconds=timeout_seconds,
                harness_dir=harness_dir,
                use_compat=use_compat,
                use_guards=use_guards,
                use_ablation=use_ablation,
                use_driver=use_driver,
                synth_retries=synth_retries,
            )
        results.append(result)
        if on_result is not None:
            on_result(index, result)
    return results


def _run_one(
    candidate: ScanCandidate,
    *,
    index: int,
    synthesizer: HarnessSynthesizer,
    esbmc_command: list[str] | None,
    bound: int,
    timeout_seconds: int,
    harness_dir: Path,
    use_compat: bool = True,
    use_guards: bool = True,
    use_ablation: bool = True,
    use_driver: bool = True,
    synth_retries: int = 1,
) -> ScanCaseResult:
    started = time.monotonic()

    source_path = Path(candidate.file)
    if not source_path.exists():
        return _early(candidate, synthesizer.model, CANDIDATE_NOT_FOUND,
                      f"file not found: {candidate.file}", started)

    unit = _find_unit(preprocess_file(source_path), candidate.function)
    if unit is None:
        return _early(candidate, synthesizer.model, CANDIDATE_NOT_FOUND,
                      f"function {candidate.function!r} not found in {candidate.file}", started)

    native = None if getattr(unit, "kind", "function") == "module" else _try_native(
        candidate,
        finding_id=f"scan_{index:03d}_native",
        esbmc_command=esbmc_command,
        bound=bound,
        timeout_seconds=timeout_seconds,
        harness_dir=harness_dir,
    )
    if native is not None:
        native.synth_model = synthesizer.model
        native.seconds = time.monotonic() - started
        return native

    finding = Finding(
        id=f"scan_{index:03d}",
        stage="scan_candidate",
        finding_type="suspected_bug",
        category=candidate.category,
        title="",
        explanation=candidate.note,
        evidence=[],
        verifiable=True,
        confidence="medium",
        metadata={"expression": candidate.expression},
    )

    driver_note = ""
    if use_driver and getattr(unit, "kind", "function") == "module":
        driver_note = "unsupported: module-level unit has no callable function for verbatim driver"
    elif use_driver:
        driver, driver_note = _try_driver(
            candidate, unit, finding,
            index=index, synthesizer=synthesizer, esbmc_command=esbmc_command,
            bound=bound, timeout_seconds=timeout_seconds, harness_dir=harness_dir,
            use_guards=use_guards, use_ablation=use_ablation, retries=synth_retries,
        )
        if driver is not None:
            driver.driver_note = driver_note
            driver.seconds = time.monotonic() - started
            return driver

    history: list[dict] = []
    total_tokens = 0
    total_synth_seconds = 0.0
    total_esbmc_seconds = 0.0
    repair_feedback = ""
    previous_harness = ""
    last: ScanCaseResult | None = None
    for attempt in range(1 + max(0, synth_retries)):
        result = _one_attempt(
            candidate, unit, finding,
            index=index, attempt=attempt,
            synthesizer=synthesizer, esbmc_command=esbmc_command,
            bound=bound, timeout_seconds=timeout_seconds, harness_dir=harness_dir,
            use_compat=use_compat, use_guards=use_guards, use_ablation=use_ablation,
            repair_feedback=repair_feedback,
            previous_harness=previous_harness,
        )
        result.attempts = attempt + 1
        result.seconds = time.monotonic() - started
        total_tokens += result.synth_total_tokens or 0
        total_synth_seconds += result.synth_seconds
        total_esbmc_seconds += result.esbmc_seconds
        history.append(
            {
                "attempt": attempt + 1,
                "classification": result.classification,
                "compat_reasons": result.compat_reasons,
                "esbmc_status": result.esbmc_status,
                "esbmc_summary": result.esbmc_summary,
                "error": result.error,
                "tokens": result.synth_total_tokens,
                "synth_seconds": result.synth_seconds,
                "esbmc_seconds": result.esbmc_seconds,
                "repair_feedback": repair_feedback,
            }
        )
        result.attempt_history = list(history)
        result.synth_total_tokens = total_tokens or None
        result.synth_seconds = total_synth_seconds
        result.esbmc_seconds = total_esbmc_seconds
        result.driver_note = driver_note
        last = result
        if result.classification in _CONCLUSIVE:
            return result
        if result.classification not in _RECOVERABLE:
            return result
        repair_feedback = _repair_feedback(result)
        previous_harness = result.harness

    assert last is not None
    return last


def _repair_feedback(result: ScanCaseResult) -> str:
    """Turn deterministic validator output into the next synthesis instruction."""
    if result.compat_reasons:
        return "Compatibility validation failed:\n- " + "\n- ".join(result.compat_reasons)
    if result.classification == NO_PROPERTY:
        return (
            "ESBMC generated no usable property. Add an explicit, reachable assert "
            "for the suspected bug and keep a module-level symbolic driver."
        )
    if result.esbmc_summary:
        return f"ESBMC could not verify the harness: {result.esbmc_summary}"
    return result.error or f"Harness attempt ended as {result.classification}."


def _early(
    candidate: ScanCandidate, model: str, classification: str, error: str, started: float
) -> ScanCaseResult:
    return ScanCaseResult(
        candidate=candidate,
        classification=classification,
        synth_model=model,
        error=error,
        seconds=time.monotonic() - started,
    )


def _try_native(
    candidate: ScanCandidate,
    *,
    finding_id: str,
    esbmc_command: list[str] | None,
    bound: int,
    timeout_seconds: int,
    harness_dir: Path,
) -> ScanCaseResult | None:
    """Try ESBMC's own --function/--assign-param-nondet on the real source
    first (Flow B, verification/esbmc_runner.py) -- no LLM harness, no
    abstraction gap. Returns None (fall through to harness synthesis) unless
    the run gives a verdict actually backed by a checked property:

    - `violation_found` always counts -- ESBMC's own automatic checks
      (div-by-zero, bounds, overflow, an uncaught exception) fired on the
      REAL function, independent of category.
    - `no_violation_found` only counts for the 7 categories whose bug is one
      of those automatic checks. For `assertion_violation`/`incorrect_result`
      there is no built-in property encoding the hypothesized "correct"
      behaviour (no assert exists on the real source), so an absence of
      violation here proves nothing -- same vacuous-claim risk EXP-03 found
      for a bare assert on unconstrained input (docs/v2/experiment_log.md).
    """
    parts = candidate.function.split(".")
    function_name = parts[-1]
    class_name = parts[0] if len(parts) > 1 else None
    result = run_esbmc_on_function(
        candidate.file,
        function_name,
        finding_id,
        candidate.category,
        class_name=class_name,
        esbmc_command=esbmc_command,
        bound=bound,
        timeout_seconds=timeout_seconds,
        output_dir=str(harness_dir),
    )
    if result.status == "violation_found":
        classification = CONFIRMED_NATIVE
    elif result.status == "no_violation_found" and candidate.category not in OUTCOME_CATEGORIES:
        classification = SAFE_NATIVE
    else:
        return None
    return ScanCaseResult(
        candidate=candidate,
        classification=classification,
        compat_verdict="native_function",
        esbmc_status=result.status,
        esbmc_summary=result.summary,
        esbmc_seconds=result.time_seconds,
        attempts=0,
    )


def _try_driver(
    candidate: ScanCandidate,
    unit,
    finding: Finding,
    *,
    index: int,
    synthesizer: HarnessSynthesizer,
    esbmc_command: list[str] | None,
    bound: int,
    timeout_seconds: int,
    harness_dir: Path,
    use_guards: bool,
    use_ablation: bool,
    retries: int,
) -> tuple[ScanCaseResult | None, str]:
    """Verbatim-driver method: LLM keeps the real function body and writes only
    the symbolic driver.

    Returns ``(result, note)``. ``result`` is a conclusive ScanCaseResult, or
    None to fall through to the scalar-synth fallback (function does not fit the
    method, the harness stayed invalid across retries, ESBMC was inconclusive).
    ``note`` records why in either case, so a run can be sliced by driver
    applicability without a second instrumented pass.
    """
    repair_feedback = ""
    previous_harness = ""
    tokens = 0
    synth_seconds = 0.0
    esbmc_seconds = 0.0
    invalid_reasons = ""
    invalid_count = 0

    for attempt in range(1 + max(0, retries)):
        try:
            synth = synthesizer.synthesize(
                unit, finding,
                use_guards=use_guards, style=STYLE_DRIVER,
                repair_feedback=repair_feedback, previous_harness=previous_harness,
            )
        except Exception as exc:  # noqa: BLE001 - network/API failure is reported, not raised
            print(f"  driver: synthesis failed ({exc}); falling back to scalar synth")
            return None, f"synth-failed: {exc}"

        tokens += synth.telemetry.get("total_tokens") or 0
        synth_seconds += float(synth.telemetry.get("duration_seconds") or 0.0)

        check = check_driver_harness(
            synth.harness, real_source=unit.source, function_name=unit.name,
            expression=candidate.expression,
        )
        if not check.ok:
            reason = "; ".join(check.reasons)
            if check.verdict == DRIVER_VERDICT_UNSUPPORTED:
                return None, f"unsupported: {reason}"
            invalid_count += 1
            invalid_reasons = reason
            repair_feedback = "Driver harness rejected:\n- " + "\n- ".join(check.reasons)
            previous_harness = synth.harness
            continue

        harness_path = harness_dir / f"scan_{index:03d}_{unit.name}_driver.py"
        harness_path.write_text(synth.harness, encoding="utf-8")

        esbmc = run_esbmc_direct(
            harness_path,
            esbmc_command=esbmc_command,
            bound=bound,
            timeout_seconds=timeout_seconds,
            output_dir=str(harness_dir),
        )
        esbmc_seconds += esbmc.time_seconds

        base = ScanCaseResult(
            candidate=candidate,
            classification=CONFIRMED_DRIVER,
            harness=synth.harness,
            harness_path=str(harness_path),
            compat_verdict="driver",
            esbmc_status=esbmc.status,
            esbmc_summary=esbmc.summary,
            synth_model=synthesizer.model,
            synth_total_tokens=tokens or None,
            synth_seconds=synth_seconds,
            esbmc_seconds=esbmc_seconds,
            attempts=attempt + 1,
        )

        if esbmc.status == "violation_found":
            if candidate.category in OUTCOME_CATEGORIES:
                grounding = check_outcome_grounding(synth.harness)
                if grounding.ok:
                    base.classification = CONFIRMED_DRIVER
                else:
                    base.classification = CONFIRMED_UNVERIFIED
                    base.compat_reasons = list(grounding.reasons)
            else:
                base.classification = CONFIRMED_DRIVER
            return base, "conclusive"

        if esbmc.status == "no_violation_found":
            base.classification = SAFE_DRIVER
            if use_ablation:
                report = _ablate_harness(
                    synth.harness, esbmc_command=esbmc_command,
                    bound=bound, timeout_seconds=timeout_seconds,
                )
                base.ablation_per_assumption = dict(report.per_assumption)
                if report.over_restricted:
                    base.classification = OVER_RESTRICTED
                    base.masking_assumptions = list(report.masking_assumptions)
            return base, "conclusive"

        # no_vcc_generated -> vacuous (Finding 1 shape); anything else ->
        # inconclusive. Both recoverable: retry, else fall through to scalar.
        if esbmc.status == "no_vcc_generated":
            repair_feedback = (
                "ESBMC generated 0 VCCs -- the harness verified vacuously. Make the "
                "asserted property depend on the call result and keep every "
                "precondition an __ESBMC_assume."
            )
        else:
            repair_feedback = f"ESBMC was inconclusive ({esbmc.summary})."
        previous_harness = synth.harness

    if invalid_count:
        return None, f"invalid x{invalid_count}: {invalid_reasons}"
    return None, f"inconclusive: {esbmc.summary}"


def _one_attempt(
    candidate: ScanCandidate,
    unit,
    finding: Finding,
    *,
    index: int,
    attempt: int,
    synthesizer: HarnessSynthesizer,
    esbmc_command: list[str] | None,
    bound: int,
    timeout_seconds: int,
    harness_dir: Path,
    use_compat: bool,
    use_guards: bool,
    use_ablation: bool,
    repair_feedback: str,
    previous_harness: str,
) -> ScanCaseResult:
    started = time.monotonic()
    result = ScanCaseResult(
        candidate=candidate,
        classification=SYNTH_FAILED,
        synth_model=synthesizer.model,
    )

    try:
        synth_result = synthesizer.synthesize(
            unit,
            finding,
            use_guards=use_guards,
            repair_feedback=repair_feedback,
            previous_harness=previous_harness,
        )
    except Exception as exc:  # noqa: BLE001 - network/API failure is reported, not raised
        result.classification = SYNTH_FAILED
        result.error = f"synthesis failed: {exc}"
        result.seconds = time.monotonic() - started
        return result

    result.harness = synth_result.harness
    result.synth_total_tokens = synth_result.telemetry.get("total_tokens")
    result.synth_seconds = float(synth_result.telemetry.get("duration_seconds") or 0.0)

    if use_compat:
        compat = check_harness(synth_result.harness, category=candidate.category)
        result.compat_verdict = compat.verdict
        result.compat_reasons = list(compat.reasons)
        if not compat.ok:
            result.classification = (
                UNSUPPORTED_HARNESS
                if compat.verdict == VERDICT_UNSUPPORTED
                else INVALID_HARNESS
            )
            result.seconds = time.monotonic() - started
            return result
    else:
        result.compat_verdict = "skipped"

    suffix = f"_try{attempt}" if attempt else ""
    harness_path = harness_dir / f"scan_{index:03d}_{unit.name}{suffix}.py"
    harness_path.write_text(synth_result.harness, encoding="utf-8")
    result.harness_path = str(harness_path)

    esbmc = run_esbmc_direct(
        harness_path,
        esbmc_command=esbmc_command,
        bound=bound,
        timeout_seconds=timeout_seconds,
        output_dir=str(harness_dir),
    )
    result.esbmc_status = esbmc.status
    result.esbmc_summary = esbmc.summary
    result.esbmc_seconds = esbmc.time_seconds

    result.classification = _classify_esbmc(esbmc.status)
    if result.classification == CONFIRMED_ON_ABSTRACTION:
        raw_violated = esbmc.details.get("violated_properties")
        violated = [str(v).strip() for v in raw_violated] if isinstance(raw_violated, list) else []
        if not violated:
            fallback = str(esbmc.details.get("property_kind", "")).strip()
            violated = [fallback] if fallback else []
        if EXPECTED_PROPERTY_MARKER not in violated:
            if violated and all(_looks_like_cover_negation(v) for v in violated):
                # --multi-property showed only __ESBMC_cover's own inverted-assert
                # failing (proving the bug input is reachable, as intended); the
                # marked assert itself was never violated, so this run is safe on
                # this abstraction, not an invalid harness.
                result.classification = SAFE_ON_ABSTRACTION
                result.esbmc_status = "no_violation_found"
            else:
                result.classification = INVALID_HARNESS
                result.compat_verdict = "invalid_harness"
                result.compat_reasons = [
                    (
                        "ESBMC failed a different property "
                        f"({violated[0] if violated else 'unknown'}), not the marked expected assertion"
                    )
                ]
    if result.classification == CONFIRMED_ON_ABSTRACTION and candidate.category in OUTCOME_CATEGORIES:
        grounding = check_outcome_grounding(synth_result.harness)
        if not grounding.ok:
            result.compat_reasons = list(grounding.reasons)
            result.classification = CONFIRMED_UNVERIFIED

    if use_ablation and result.classification == SAFE_ON_ABSTRACTION:
        report = _ablate_harness(
            synth_result.harness,
            esbmc_command=esbmc_command,
            bound=bound,
            timeout_seconds=timeout_seconds,
        )
        result.ablation_per_assumption = dict(report.per_assumption)
        if report.over_restricted:
            result.classification = OVER_RESTRICTED
            result.masking_assumptions = list(report.masking_assumptions)

    result.seconds = time.monotonic() - started
    return result


def _looks_like_cover_negation(property_kind: str) -> bool:
    """True when a violated property's text is ESBMC's own inverted-assert form
    for __ESBMC_cover(cond) (compiled internally as assert(!cond)), not a real
    exception or the harness's own marked assert.

    Confirmed empirically (2026-09-04, real ESBMC 8.4.0, --multi-property): a
    tripped __ESBMC_cover always reports as "assertion !(<condition>)"; genuine
    exceptions (invalid int() conversion, uncaught exception on a missing dict
    key) never take this shape. See docs/v2/experiment_log.md EXP-01.
    """
    return property_kind.startswith("assertion !(")


def _classify_esbmc(status: str) -> str:
    if status == "skipped":
        return ESBMC_UNAVAILABLE
    if status == "violation_found":
        return CONFIRMED_ON_ABSTRACTION
    if status in ("no_vcc_generated", "unsupported_case"):
        return NO_PROPERTY
    if status == "no_violation_found":
        return SAFE_ON_ABSTRACTION
    return ESBMC_INCONCLUSIVE


def _ablate_harness(
    harness: str,
    *,
    esbmc_command: list[str] | None,
    bound: int,
    timeout_seconds: int,
) -> AblationReport:
    def run(variant_source: str) -> str:
        status = _verdict_on_source(
            variant_source,
            esbmc_command=esbmc_command,
            bound=bound,
            timeout_seconds=timeout_seconds,
        )
        return FAILED if status == "violation_found" else status.upper()

    return ablate(harness, run)


def _verdict_on_source(
    source: str,
    *,
    esbmc_command: list[str] | None,
    bound: int,
    timeout_seconds: int,
) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "ablated.py"
        path.write_text(source, encoding="utf-8")
        esbmc = run_esbmc_direct(
            path,
            esbmc_command=esbmc_command,
            bound=bound,
            timeout_seconds=timeout_seconds,
            output_dir=tmp,
        )
    return esbmc.status
